name: Run Unit Tests

on:
  push:
    branches:
      - task-1
  pull_request:
    branches:
      - task-1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Make sure you have a requirements.txt file

    - name: Run unit tests
      run: |
        pytest  # Adjust the command if you're using a different testing framework
